/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AiFullstackRouteImport } from './routes/ai-fullstack'
import { Route as AiAutomationRouteImport } from './routes/ai-automation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CybersecurityIndexRouteImport } from './routes/cybersecurity.index'
import { Route as CybersecurityProfessionalRouteImport } from './routes/cybersecurity.professional'
import { Route as CybersecurityFoundationRouteImport } from './routes/cybersecurity.foundation'
import { Route as DomainProgramRouteImport } from './routes/$domain.$program'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFullstackRoute = AiFullstackRouteImport.update({
  id: '/ai-fullstack',
  path: '/ai-fullstack',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomationRoute = AiAutomationRouteImport.update({
  id: '/ai-automation',
  path: '/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecurityIndexRoute = CybersecurityIndexRouteImport.update({
  id: '/cybersecurity/',
  path: '/cybersecurity/',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecurityProfessionalRoute =
  CybersecurityProfessionalRouteImport.update({
    id: '/cybersecurity/professional',
    path: '/cybersecurity/professional',
    getParentRoute: () => rootRouteImport,
  } as any)
const CybersecurityFoundationRoute = CybersecurityFoundationRouteImport.update({
  id: '/cybersecurity/foundation',
  path: '/cybersecurity/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainProgramRoute = DomainProgramRouteImport.update({
  id: '/$domain/$program',
  path: '/$domain/$program',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/ai-fullstack': typeof AiFullstackRoute
  '/team': typeof TeamRoute
  '/$domain/$program': typeof DomainProgramRoute
  '/cybersecurity/foundation': typeof CybersecurityFoundationRoute
  '/cybersecurity/professional': typeof CybersecurityProfessionalRoute
  '/cybersecurity/': typeof CybersecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/ai-fullstack': typeof AiFullstackRoute
  '/team': typeof TeamRoute
  '/$domain/$program': typeof DomainProgramRoute
  '/cybersecurity/foundation': typeof CybersecurityFoundationRoute
  '/cybersecurity/professional': typeof CybersecurityProfessionalRoute
  '/cybersecurity': typeof CybersecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/ai-fullstack': typeof AiFullstackRoute
  '/team': typeof TeamRoute
  '/$domain/$program': typeof DomainProgramRoute
  '/cybersecurity/foundation': typeof CybersecurityFoundationRoute
  '/cybersecurity/professional': typeof CybersecurityProfessionalRoute
  '/cybersecurity/': typeof CybersecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-automation'
    | '/ai-fullstack'
    | '/team'
    | '/$domain/$program'
    | '/cybersecurity/foundation'
    | '/cybersecurity/professional'
    | '/cybersecurity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-automation'
    | '/ai-fullstack'
    | '/team'
    | '/$domain/$program'
    | '/cybersecurity/foundation'
    | '/cybersecurity/professional'
    | '/cybersecurity'
  id:
    | '__root__'
    | '/'
    | '/ai-automation'
    | '/ai-fullstack'
    | '/team'
    | '/$domain/$program'
    | '/cybersecurity/foundation'
    | '/cybersecurity/professional'
    | '/cybersecurity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAutomationRoute: typeof AiAutomationRoute
  AiFullstackRoute: typeof AiFullstackRoute
  TeamRoute: typeof TeamRoute
  DomainProgramRoute: typeof DomainProgramRoute
  CybersecurityFoundationRoute: typeof CybersecurityFoundationRoute
  CybersecurityProfessionalRoute: typeof CybersecurityProfessionalRoute
  CybersecurityIndexRoute: typeof CybersecurityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-fullstack': {
      id: '/ai-fullstack'
      path: '/ai-fullstack'
      fullPath: '/ai-fullstack'
      preLoaderRoute: typeof AiFullstackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-automation': {
      id: '/ai-automation'
      path: '/ai-automation'
      fullPath: '/ai-automation'
      preLoaderRoute: typeof AiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity/': {
      id: '/cybersecurity/'
      path: '/cybersecurity'
      fullPath: '/cybersecurity/'
      preLoaderRoute: typeof CybersecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity/professional': {
      id: '/cybersecurity/professional'
      path: '/cybersecurity/professional'
      fullPath: '/cybersecurity/professional'
      preLoaderRoute: typeof CybersecurityProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity/foundation': {
      id: '/cybersecurity/foundation'
      path: '/cybersecurity/foundation'
      fullPath: '/cybersecurity/foundation'
      preLoaderRoute: typeof CybersecurityFoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$domain/$program': {
      id: '/$domain/$program'
      path: '/$domain/$program'
      fullPath: '/$domain/$program'
      preLoaderRoute: typeof DomainProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAutomationRoute: AiAutomationRoute,
  AiFullstackRoute: AiFullstackRoute,
  TeamRoute: TeamRoute,
  DomainProgramRoute: DomainProgramRoute,
  CybersecurityFoundationRoute: CybersecurityFoundationRoute,
  CybersecurityProfessionalRoute: CybersecurityProfessionalRoute,
  CybersecurityIndexRoute: CybersecurityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
